#!/bin/bash
#
# initscripts-macvlan
# Copyright (C) 2014 Lars Kellogg-Stedman
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /etc/init.d/functions

cd /etc/sysconfig/network-scripts
. ./network-functions

[ -f ../network ] && . ../network

CONFIG=${1}

need_config ${CONFIG}

source_config

if [ -z "$MACVLAN_PARENT" ]; then
    net_log "Macvlan must set master device name, please set MACVLAN_PARENT"
    exit 1
fi

if [ -z "$DEVICE" ]; then
    net_log "Macvlan must set device name, please set DEVICE"
    exit 1
fi


ip link add \
	link ${MACVLAN_PARENT} \
	name ${DEVICE} \
	type ${TYPE:-macvlan} mode ${MACVLAN_MODE:-bridge}

net_log "create macvlan use ${MACVLAN_MODE:-bridge} mode " info 

OTHERSCRIPT="/etc/sysconfig/network-scripts/ifup-eth"

exec ${OTHERSCRIPT} ${CONFIG}

